# This is the work flow to generate preview links for Pull Requests
name: PR-Preview-Generator
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env: # Or as an environment variable
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
          DEPLOY_DOMAIN: pr-${{ github.event.number }}-heyhey.surge.sh
        run: surge ./ $DEPLOY_DOMAIN --token $SURGE_TOKEN
        
