# This is the work flow to generate preview links for Pull Requests
name: CI
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Surge
        run: npm i -g surge
      - name: Run Surge Deployment Script
        env: # Or as an environment variable
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: | 
            echo $SURGE_LOGIN
            surge ./ https://secret-key-t.surge.sh/ --token $SURGE_TOKEN
        
