# This is the work flow to generate preview links for Pull Requests
name: PR-Preview-Generator
on:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env: # Or as an environment variable
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: | 
            echo $PR_NUMBER
            surge ./ https://secret-key-t.surge.sh/ --token $SURGE_TOKEN
        
